name: Release to Play Store

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}

    steps:
      - uses: actions/checkout@v4

      - name: Set version name as env variable
        run: echo "version_name=$(echo $(grep versionName ./app/build.gradle.kts | awk -F '"' '{print $2}'))" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build aab
        run: bash build-aab.sh

      - name: Publish to Play Store (Internal)
        run: ./gradlew publishGoogleReleaseBundle

      - name: Save aab
        uses: actions/upload-artifact@v4
        with:
          name: PlainApp-${{ env.version_name }}.aab
          path: ./PlainApp-${{ env.version_name }}.aab
